package com.blockchain;

public class Constants {

    /* Secret -> SB4ARDMZMMRDKINGGG6SRLQLI3R7P5P4OM6TFSST56IR42TLWYZKTUZO
     public key ->  GADBZNODG4ATATBNREYFEKGIBRFJI5I5FF2T4F7CZ5EA7AYZGKJZHZX4
     */
    public final static String RAJESH_PUB_KEY = "GADBZNODG4ATATBNREYFEKGIBRFJI5I5FF2T4F7CZ5EA7AYZGKJZHZX4";
    public final static String RAJESH_SEED_KEY = "SB4ARDMZMMRDKINGGG6SRLQLI3R7P5P4OM6TFSST56IR42TLWYZKTUZO";


    /*
     Secret -> SD4E4O2K3HB3GGCYPZK4ZLZANRWDWEQFZZBDMESFPSDDQWDGJ43LYWFI
     public key ->  GCD6LCZQ7FHEKJNTTRFIYIRZ2MJCOYKTEZHXAIEO2YCFSCBSTUIWIAWL
     */

    public final static String ADAM_PUB_KEY = "GCD6LCZQ7FHEKJNTTRFIYIRZ2MJCOYKTEZHXAIEO2YCFSCBSTUIWIAWL";
    public final static String ADAM_SEED_KEY = "SD4E4O2K3HB3GGCYPZK4ZLZANRWDWEQFZZBDMESFPSDDQWDGJ43LYWFI";


    /**
     Secret -> SCVFCNFCFB2U4CPFEOIN2WC5IGJPH4JXNKULUN4OZBT76IA2LR56SRJE
     public key ->  GCCM5YFJTVLAWL4XJUAELM7D7NTS4KTDEHY6DXGGXOWRELBD2BMUSDSQ
     */
    public final static String HINA_PUB_KEY = "GCCM5YFJTVLAWL4XJUAELM7D7NTS4KTDEHY6DXGGXOWRELBD2BMUSDSQ";
    public final static String HINA_SEED_KEY = "SCVFCNFCFB2U4CPFEOIN2WC5IGJPH4JXNKULUN4OZBT76IA2LR56SRJE";

}
